### ISSUE TITLE
Install BaseVar erro

### ISSUE THREAD

**Issue by amygu20** [ShujiaHuang/ShujiaHuang#3]
Hello, 

I am trying to use BaseVar on HPC Cluster but have some error when runing the last line `python setup.py install`

Here is the error:

Error compiling Cython file:
------------------------------------------------------------
...
Date: 2019-05-29
"""
cdef class FastaIndex:
    cdef long int n_targets
    cdef dict references
    cpdef dict target_name
          ^
------------------------------------------------------------

basevar/io/fasta.pxd:9:10: Variables cannot be declared with 'cpdef'. Use 'cdef' instead.

Error compiling Cython file:
------------------------------------------------------------
...
"""
cdef class FastaIndex:
    cdef long int n_targets
    cdef dict references
    cpdef dict target_name
    cpdef dict target_length
          ^
------------------------------------------------------------

basevar/io/fasta.pxd:10:10: Variables cannot be declared with 'cpdef'. Use 'cdef' instead.
Traceback (most recent call last):
  File "/group/zhougrp4/amy/f34_AIL_LowPath_WGS/01_week2/04_basevar/basevar-0.8.0/setup.py", line 117, in <module>
    ext_modules=cythonize(extensions),
                ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amy0220/mambaforge/envs/basever/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
    cythonize_one(*args)
  File "/home/amy0220/mambaforge/envs/basever/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: basevar/caller/basetypeprocess.pyx
(basever) [farm:basevar-0.8.0]-[157] Error compiling Cython file:
------------------------------------------------------------
...
Date: 2019-05-29
"""
cdef class FastaIndex:
    cdef long int n_targets
    cdef dict references
    cpdef dict target_name
          ^
------------------------------------------------------------

basevar/io/fasta.pxd:9:10: Variables cannot be declared with 'cpdef'. Use 'cdef' instead.

Here are the steps I did

`conda create -n basever
conda install conda-forge::cython` #(v3.0.8)

I also tried a different verson `conda install anaconda::cython` but still have the same error code

Then i set path to: 

`export C_INCLUDE_PATH=/share/apps/22.04/spack/spack-v0.19.1/opt/spack/linux-ubuntu22.04-x86_64_v2/gcc-9.5.0/htslib-1.14-7jx6t3cbv5pokdwnpbwnbj63slo2bneo/include

export LIBRARY_PATH=/share/apps/22.04/spack/spack-v0.19.1/opt/spack/linux-ubuntu22.04-x86_64_v2/gcc-9.5.0/htslib-1.14-7jx6t3cbv5pokdwnpbwnbj63slo2bneo/lib

export LD_LIBRARY_PATH=/share/apps/22.04/spack/spack-v0.19.1/opt/spack/linux-ubuntu22.04-x86_64_v2/gcc-9.5.0/htslib-1.14-7jx6t3cbv5pokdwnpbwnbj63slo2bneo/lib
`

Thank you very much for your time. 

Best,
Amy

**Comment by amygu20** [comment]
I was able to get Basever installed by installing python 2 frist then installed cython under the same envriment


Then i also installed the fellowing items under the same envriment: 

`conda install conda-forge::scipy
conda install conda-forge::scikit-learn
conda install conda-forge::logbook
conda install conda-forge::numpy`


However, I am getting the fellowing error code when trying to run it


pkg_resources.DistributionNotFound: The 'scikit-learn>=0.20.2' distribution was not found and is required by basevar
